dependencies {
	implementation project(':application')
	implementation project(':domain')

	implementation 'org.springframework.boot:spring-boot-autoconfigure'

	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
