dependencies {
	implementation project(':application')
	implementation project(':domain')

	implementation 'org.springframework.boot:spring-boot'
	implementation 'org.springframework.boot:spring-boot-autoconfigure'
	implementation 'io.lettuce:lettuce-core'

	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation 'org.assertj:assertj-core'
}
