apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - database-identity-config.yaml
  - app-deployment.yaml
  - app-service.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - mysql-network-policy.yaml
