apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: baton-go-mysql-runtime-user-init
    files:
      - 10-create-runtime-user.sh=mysql-runtime-user-init.sh
    options:
      labels:
        app.kubernetes.io/name: baton-go
        app.kubernetes.io/component: database

resources:
  - database-identity-config.yaml
  - database-migration-job.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-network-policy.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - mysql-network-policy.yaml
