plugins {
	id 'org.springframework.boot'
}

dependencies {
	implementation project(':application')
	implementation project(':adapter-out-external')

	runtimeOnly 'com.mysql:mysql-connector-j'

	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation 'org.assertj:assertj-core'
}

tasks.named('bootJar') {
	archiveFileName = 'baton-go-guard-binding.jar'
	mainClass = 'com.personal.batongo.bootstrap.guard.LinkCodeKeyGuardBindingCli'
}
